// Package transport provides loopback detection and the shared plaintext
// transport warnings emitted by the Phoenix server, CLI, and MCP transport.
//
// Phoenix is LAN-scoped by design: plaintext HTTP on loopback is the safe,
// supported default, and TLS must be enabled the moment traffic crosses a
// wire. Nothing here refuses to run — the job of this package is to make
// the silent transition from loopback to network exposure loud.
package transport

import (
	"fmt"
	"net"
	"net/url"
	"strings"
)

// IsLoopbackHost reports whether host (an IP literal or hostname, no port)
// refers unambiguously to the loopback interface. The empty host (a bind
// like ":9090") means all interfaces and is NOT loopback. Hostnames other
// than "localhost" are not resolved — they are treated as non-loopback so
// that ambiguity fails toward warning.
func IsLoopbackHost(host string) bool {
	if host == "" {
		return false
	}
	if strings.EqualFold(host, "localhost") {
		return true
	}
	if ip := net.ParseIP(host); ip != nil {
		return ip.IsLoopback()
	}
	return false
}

// IsLoopbackListen reports whether a listen address ("host:port") binds
// only the loopback interface. Addresses that fail to parse are treated
// as non-loopback (warn on ambiguity).
func IsLoopbackListen(addr string) bool {
	host, _, err := net.SplitHostPort(addr)
	if err != nil {
		// No port (or unparseable): judge the whole string as a host.
		return IsLoopbackHost(addr)
	}
	return IsLoopbackHost(host)
}

// IsPlaintextNonLoopbackURL reports whether rawurl is a plain http:// URL
// pointing at a non-loopback host — the case where bearer tokens and secret
// values would cross a network unencrypted. https:// URLs and loopback
// http:// URLs return false. Unparseable URLs return false (the request
// will fail on its own; there is nothing useful to warn about).
func IsPlaintextNonLoopbackURL(rawurl string) bool {
	u, err := url.Parse(rawurl)
	if err != nil {
		return false
	}
	if !strings.EqualFold(u.Scheme, "http") {
		return false
	}
	return !IsLoopbackHost(u.Hostname())
}

// ServerPlaintextWarning returns the multi-line startup warning for a
// Phoenix server binding a non-loopback address without TLS. dashboard
// adds the dashboard-specific exposure line.
func ServerPlaintextWarning(listen string, dashboard bool) string {
	var b strings.Builder
	line := func(format string, args ...interface{}) {
		if format == "" {
			b.WriteString("!!\n")
			return
		}
		fmt.Fprintf(&b, "!! "+format+"\n", args...)
	}
	line("------------------------------------------------------------------")
	line("INSECURE TRANSPORT: PLAINTEXT HTTP ON A NON-LOOPBACK ADDRESS")
	line("")
	line("server.listen is %q and TLS is not enabled.", listen)
	line("Every request to this server crosses the network unencrypted.")
	line("Anything on the same network segment can read:")
	line("  - bearer tokens (each one grants its full ACL scope)")
	line("  - every secret value this server returns")
	if dashboard {
		line("  - dashboard passwords and session cookies")
	}
	line("")
	line("Fix (one line in config.json):")
	line("  \"tls\": { \"enabled\": true }")
	line("The server certificate generated by --init is used automatically.")
	line("Clients connect with https:// and PHOENIX_CA_CERT=<data-dir>/ca.crt.")
	line("If clients use a LAN IP or hostname, add it to the certificate:")
	line("  phoenix-server --reissue-cert --san <ip-or-hostname> --config <config>")
	line("See docs/lan-deployment.md.")
	b.WriteString("!! ------------------------------------------------------------------")
	return b.String()
}

// MCPPlaintextWarning returns the multi-line startup warning for the MCP
// Streamable HTTP transport listening on a non-loopback address without TLS.
func MCPPlaintextWarning(listen string) string {
	var b strings.Builder
	line := func(format string, args ...interface{}) {
		if format == "" {
			b.WriteString("!!\n")
			return
		}
		fmt.Fprintf(&b, "!! "+format+"\n", args...)
	}
	line("------------------------------------------------------------------")
	line("INSECURE TRANSPORT: PLAINTEXT HTTP ON A NON-LOOPBACK ADDRESS")
	line("")
	line("The MCP HTTP transport is listening on %q without TLS.", listen)
	line("Every request crosses the network unencrypted. Anything on the")
	line("same network segment can read:")
	line("  - the MCP bearer token (full access to this MCP server)")
	line("  - every secret value returned to MCP clients")
	line("")
	line("Fix: pass --tls-cert and --tls-key (the Phoenix --init server")
	line("certificate works: <data-dir>/server.crt and <data-dir>/server.key),")
	line("or bind to 127.0.0.1 and keep MCP clients on this host.")
	line("See docs/lan-deployment.md.")
	b.WriteString("!! ------------------------------------------------------------------")
	return b.String()
}

// ClientPlaintextWarning returns a short warning for a client (CLI) that is
// about to send bearer tokens over plaintext HTTP to a non-loopback server.
// Returns "" when serverURL does not warrant a warning.
func ClientPlaintextWarning(serverURL string) string {
	if !IsPlaintextNonLoopbackURL(serverURL) {
		return ""
	}
	return fmt.Sprintf(
		"WARNING: PHOENIX_SERVER is plaintext http:// to a non-loopback address (%s).\n"+
			"Bearer tokens and secret values will cross the network unencrypted.\n"+
			"Fix: enable the server's \"tls\" config block, switch this URL to https://,\n"+
			"and set PHOENIX_CA_CERT to the Phoenix CA certificate (docs/lan-deployment.md).",
		serverURL)
}
